services:
  nethermind_execution_l2:
    image: nethermindeth/nethermind:surge-177139a04
    container_name: l2-nethermind-execution-client
    restart: unless-stopped
    pull_policy: always
    stop_grace_period: 3m
    tty: true
    volumes:
      - ./jwtsecret:/tmp/jwt/jwtsecret
      - ./chainspec.json:/chainspec.json
    networks:
      - surge
    ports:
      - 30313:30313/tcp
      - 30313:30313/udp
      - 8018:8018
      - 8547:8547
      - 8548:8548
      - 8552:8552
    command:
      - --config=none
      - --datadir=/data/taiko-geth
      - --Init.ChainSpecPath=/chainspec.json
      - --Init.GenesisHash=0xbeced3738f1246571cccabc82a1e6cbd9ed9d5f7ed2b6c7ded28f9722317bd9e
      - --Init.DiscoveryEnabled=false
      - --Metrics.Enabled=true
      - --Metrics.ExposePort=8018
      - --JsonRpc.Enabled=true
      - --JsonRpc.EnabledModules=[debug,eth,net,web3,txpool,rpc,subscribe,trace,personal,proof,parity,health]
      - --JsonRpc.Host=0.0.0.0
      - --JsonRpc.Port=8547
      - --JsonRpc.WebSocketsPort=8548
      - --JsonRpc.JwtSecretFile=/tmp/jwt/jwtsecret
      - --JsonRpc.EngineHost=0.0.0.0
      - --JsonRpc.EnginePort=8552
      - --Network.DiscoveryPort=30313
      - --Network.P2PPort=30313
      - --Sync.FastSync=false
      - --Sync.SnapSync=false
      - --HealthChecks.Enabled=true
      - --log=${NETHERMIND_OP_LOG_LEVEL}
      - --JsonRpc.MaxBatchResponseBodySize=335544320
      - --JsonRpc.MaxBatchSize=102400
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'echo > /dev/tcp/localhost/8547'"]
      interval: 2s
      timeout: 2s
      retries: 15
      start_period: 10s
    profiles:
      - nethermind_execution_l2
      - proposer
      - blockscout

  taiko_client_driver:
    image: nethsurge/taiko-client:f042ca8
    container_name: l2-taiko-consensus-client
    restart: unless-stopped
    pull_policy: always
    depends_on:
      - nethermind_execution_l2
    volumes:
      - ./execution-data-taiko:/data/taiko-geth
      - ./jwtsecret:/tmp/jwt/jwtsecret
    networks:
      - surge
    entrypoint:
      - taiko-client
    command:
      - driver
      - --l1.ws=${L1_ENDPOINT_WS}
      - --l2.ws=ws://l2-nethermind-execution-client:8548
      - --l1.beacon=${L1_BEACON_HTTP}
      - --l2.auth=http://l2-nethermind-execution-client:8552
      - --taikoL1=${TAIKO_L1_ADDRESS}
      - --taikoL2=${TAIKO_L2_ADDRESS}
      - --jwtSecret=/tmp/jwt/jwtsecret
    profiles:
      - nethermind_execution_l2
      - proposer
      - blockscout

  taiko_client_proposer:
    image: nethsurge/taiko-client:f042ca8
    container_name: l2-taiko-proposer-client
    restart: unless-stopped
    pull_policy: always
    depends_on:
      - nethermind_execution_l2
      - taiko_client_driver
    volumes:
      - ./execution-data-taiko:/data/taiko-geth
      - ./jwtsecret:/tmp/jwt/jwtsecret
    networks:
      - surge
    entrypoint:
      - taiko-client
    command:
      - proposer
      - --l1.ws=${L1_ENDPOINT_WS}
      - --l2.http=http://l2-nethermind-execution-client:8547
      - --l2.auth=http://l2-nethermind-execution-client:8552
      - --taikoL1=${TAIKO_L1_ADDRESS}
      - --taikoL2=${TAIKO_L2_ADDRESS}
      - --jwtSecret=/tmp/jwt/jwtsecret
      - --l1.proposerPrivKey=${L1_PROPOSER_PRIVATE_KEY}
      - --l2.suggestedFeeRecipient=${L2_SUGGESTED_FEE_RECIPIENT}
      - --tx.notInMempoolTimeout=30s
      - --tx.resubmissionTimeout=10s
      - --epoch.interval=5s
      # - --surge.gasNeededForProposingBlock=165000
      # - --surge.gasNeededForProvingBlock=100000
      # - --surge.offChainCosts=50000000000000
      # - --surge.priceFluctuationModifier=15
      # - --verbosity=4
      # conditioned
      # - --epoch.minTip ${EPOCH_MIN_TIP}
      # - --proverSet ${PROVER_SET}
      # - --txPool.localsOnly
      # - --txPool.locals ${TXPOOL_LOCALS}
      # - --l1.blobAllowed
      # - --tx.feeLimitMultiplier ${TX_FEE_LIMIT_MULTIPLIER}
      # - --tx.feeLimitThreshold ${TX_FEE_LIMIT_THRESHOLD}
      # - --tx.gasLimit ${TX_GAS_LIMIT}
      # - --tx.minBaseFee ${TX_MIN_BASEFEE}
      # - --tx.minTipCap ${TX_MIN_TIP_CAP}
      # - --tx.notInMempoolTimeout ${TX_NOT_IN_MEMPOOL}
      # - --tx.numConfirmations ${TX_NUM_CONFIRMATIONS}
      # - --tx.receiptQueryInterval ${TX_RECEIPT_QUERY}
      # - --tx.resubmissionTimeout ${TX_RESUBMISSION}
      # - --tx.safeAbortNonceTooLowCount ${TX_SAFE_ABORT_NONCE_TOO_LOW}
      # - --tx.sendTimeout ${TX_SEND_TIMEOUT}
    profiles:
      - proposer
      - blockscout

  taiko_client_prover_relayer:
    image: nethsurge/taiko-client:f042ca8
    container_name: l2-taiko-prover-relayer-client
    restart: unless-stopped
    pull_policy: always
    depends_on:
      - nethermind_execution_l2
      - taiko_client_driver
    networks:
      - surge
    entrypoint:
      - taiko-client
    command:
      - prover
      - --l1.ws=${L1_ENDPOINT_WS}
      - --l2.ws=ws://l2-nethermind-execution-client:8548
      - --l2.http=http://l2-nethermind-execution-client:8547
      - --taikoL1=${TAIKO_L1_ADDRESS}
      - --taikoL2=${TAIKO_L2_ADDRESS}
      - --l1.proverPrivKey=${L1_PROPOSER_PRIVATE_KEY}
      - --prover.capacity=${PROVER_CAPACITY}
      - --tx.notInMempoolTimeout=30s
      - --tx.resubmissionTimeout=10s
      - --raiko.host.zkvm=${RAIKO_HOST_ZKVM}
      - --raiko.host=${RAIKO_HOST_ZKVM}
      - --raiko.requestTimeout=${RAIKO_REQUEST_TIMEOUT}
      # conditioned
      # - --proverSet ${PROVER_SET}
      # - --prover.allowance ${TOKEN_ALLOWANCE}
      # - --prover.minEthBalance ${MIN_ETH_BALANCE}
      # - --prover.minTaikoTokenBalance ${MIN_TAIKO_BALANCE}
      # - --prover.proveUnassignedBlocks
      # - --tx.feeLimitMultiplier ${TX_FEE_LIMIT_MULTIPLIER}
      # - --tx.feeLimitThreshold ${TX_FEE_LIMIT_THRESHOLD}
      # - --tx.gasLimit ${TX_GAS_LIMIT}
      # - --tx.minBaseFee ${TX_MIN_BASEFEE}
      # - --tx.minTipCap ${TX_MIN_TIP_CAP}
      # - --tx.notInMempoolTimeout ${TX_NOT_IN_MEMPOOL}
      # - --tx.numConfirmations ${TX_NUM_CONFIRMATIONS}
      # - --tx.receiptQueryInterval ${TX_RECEIPT_QUERY}
      # - --tx.resubmissionTimeout ${TX_RESUBMISSION}
      # - --tx.safeAbortNonceTooLowCount ${TX_SAFE_ABORT_NONCE_TOO_LOW}
      # - --tx.sendTimeout ${TX_SEND_TIMEOUT}
    profiles:
      - prover
      - blockscout

  taiko-blockscout-postgres:
    image: postgres:alpine
    container_name: taiko-blockscout-postgres
    restart: unless-stopped
    pull_policy: always
    depends_on:
      - nethermind_execution_l2
      - taiko_client_driver
    volumes:
      - ./blockscout-postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: blockscout
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MyPassword1!
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      GOSU_VERSION: 1.17
      PG_MAJOR: 17
      PG_VERSION: 17.0
      PG_SHA256: 7e276131c0fdd6b62588dbad9b3bb24b8c3498d5009328dba59af16e819109de
      DOCKER_PG_LLVM_DEPS: llvm15-dev \t\tclang15
      PGDATA: /var/lib/postgresql/data
    command:
      - "-c"
      - "max_connections=1000"
    networks:
      - surge
    profiles:
      - blockscout

  taiko-blockscout-verif:
    image: ghcr.io/blockscout/smart-contract-verifier:v1.6.0
    container_name: taiko-blockscout-verif
    restart: unless-stopped
    pull_policy: always
    depends_on:
      - nethermind_execution_l2
      - taiko_client_driver
    ports:
      - 8050:8050
    environment:
      SMART_CONTRACT_VERIFIER__SERVER__HTTP__ADDR: 0.0.0.0:8050
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      APP_USER: app
      SMART_CONTRACT_VERIFIER__SOLIDITY__ENABLED: true
      SMART_CONTRACT_VERIFIER__SOLIDITY__FETCHER__LIST__LIST_URL: https://solc-bin.ethereum.org/linux-amd64/list.json
    command:
      - "./smart-contract-verifier-server"
    networks:
      - surge
    profiles:
      - blockscout

  taiko-blockscout:
    image: blockscout/blockscout:6.6.0
    container_name: taiko-blockscout
    restart: unless-stopped
    pull_policy: always
    depends_on:
      - nethermind_execution_l2
      - taiko_client_driver
    ports:
      - 4000:4000
    environment:
      DATABASE_URL: postgresql://postgres:MyPassword1!@taiko-blockscout-postgres:5432/blockscout
      API_V2_ENABLED: true
      ETHEREUM_JSONRPC_VARIANT: nethermind
      MICROSERVICE_SC_VERIFIER_URL: http://taiko-blockscout-verif:8050/api
      ETHEREUM_JSONRPC_HTTP_URL: http://execution-taiko-l2-client:8547/
      INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER: true
      SUBNETWORK: Kurtosis
      ETHEREUM_JSONRPC_TRACE_URL: http://execution-taiko-l2-client:8547/
      COIN: ETH
      MICROSERVICE_SC_VERIFIER_TYPE: sc_verifier
      PORT: 4000
      MICROSERVICE_SC_VERIFIER_ENABLED: true
      ECTO_USE_SSL: false
      SECRET_KEY_BASE: 56NtB48ear7+wMSf0IQuWDAAazhpb31qyc7GiyspBP2vh7t5zlCsF5QDv76chXeN
      CHAIN_ID: 763374
      SHOW_TESTNET_LABEL: true
      DISABLE_EXCHANGE_RATES: true
      DISABLE_KNOWN_TOKENS: true
      INDEXER_INTERNAL_TRANSACTIONS_BATCH_SIZE: 10000
      INDEXER_HIDE_INDEXING_PROGRESS_ALERT: false
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      RELEASE_VERSION: 6.6.0
      CHAIN_TYPE:
      BRIDGED_TOKENS_ENABLED:
      BLOCKSCOUT_VERSION: v6.6.0-beta
      SMART_CONTRACT_VERIFIER__SOLIDITY__ENABLED: true
      SMART_CONTRACT_VERIFIER__SOLIDITY__FETCHER__LIST__LIST_URL: https://solc-bin.ethereum.org/linux-amd64/list.json
    command:
      - "/bin/sh"
      - "-c"
      - "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    networks:
      - surge
    profiles:
      - blockscout

  # prometheus:
  #   image: prom/prometheus:latest
  #   restart: unless-stopped
  #   ports:
  #     - ${PORT_PROMETHEUS}:9090
  #   depends_on:
  #     - nethermind_execution_l2
  #     - taiko_client_driver
  #   volumes:
  #     - ./docker/prometheus/l2:/etc/prometheus
  #     - prometheus_data:/prometheus
  #   command:
  #     - --log.level=debug
  #     - --config.file=/etc/prometheus/prometheus.yml
  #   profiles:
  #     - nethermind_execution_l2
  #     - prover
  #     - proposer

  # grafana:
  #   image: grafana/grafana:latest
  #   restart: unless-stopped
  #   ports:
  #     - ${PORT_GRAFANA}:3000
  #   depends_on:
  #     - nethermind_execution_l2
  #     - taiko_client_driver
  #     - prometheus
  #   environment:
  #     - GF_PATHS_CONFIG=/etc/grafana/custom/settings.ini
  #     - GF_PATHS_PROVISIONING=/etc/grafana/custom/provisioning
  #     - GF_LOG_LEVEL=WARN
  #   volumes:
  #     - ./docker/grafana/custom/settings.ini:/etc/grafana/custom/settings.ini
  #     - ./docker/grafana/custom/l2/provisioning/:/etc/grafana/custom/provisioning/
  #     - grafana_data:/var/lib/grafana
  #   profiles:
  #     - nethermind_execution_l2
  #     - prover
  #     - proposer

# volumes:
#   prometheus_data:
#   grafana_data:

networks:
  surge:
    name: surge-network
