services:
  pacaya-deployer:
    image: ${PACAYA_PROTOCOL_IMAGE}
    container_name: pacaya-deployer
    pull_policy: always
    volumes:
      - ./deployer:/deployer
      - ./deployment:/deployment
    entrypoint:
      - /bin/sh
      - -c
      - /deployer/deploy-pacaya.sh
    env_file:
      - .env
    environment:
      FOUNDRY_PROFILE: layer1
      BROADCAST: ${BROADCAST}
      VERIFY: ${VERIFY}
      SLOW: ${SLOW}
      VERIFY_ARG: ${VERIFY_ARG}
      FORK_URL: ${L1_ENDPOINT_HTTP}
      CONTRACT_OWNER: ${PUBLIC_KEY}
      PRIVATE_KEY: ${PRIVATE_KEY}
    networks:
      - surge
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      com.kurtosistech.custom.logs_enabled: "true"
      com.kurtosistech.custom.custom_network: "devnet"
    profiles:
      - pacaya-deployer

  surge-l1-deployer:
    image: ${PROTOCOL_IMAGE}
    container_name: surge-l1-deployer
    pull_policy: always
    tty: true
    volumes:
      - ./deployer:/deployer
      - ./deployment:/deployment
    entrypoint:
      - /bin/sh
      - -c
      - /deployer/deploy-surge-l1.sh
    env_file:
      - .env
    environment:
      FOUNDRY_PROFILE: layer1o
      BROADCAST: ${BROADCAST}
      VERIFY: ${VERIFY}
      SLOW: ${SLOW}
      VERIFY_ARG: ${VERIFY_ARG}
      USE_DUMMY_VERIFIER: ${USE_DUMMY_VERIFIER}
      FORK_URL: ${L1_ENDPOINT_HTTP}
      CONTRACT_OWNER: ${PUBLIC_KEY}
      PRIVATE_KEY: ${PRIVATE_KEY}
      PERMISSIONLESS_PROVING_DELAY: 42300
      GENESIS_BLOCK_HASH: ${L2_GENESIS_HASH}
      NUM_PROOF_THRESHOLD: 1
    networks:
      - surge
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      com.kurtosistech.custom.logs_enabled: "true"
      com.kurtosistech.custom.custom_network: "devnet"
    profiles:
      - l1-deployer

  surge-multicall-deployer:
    image: ${PROTOCOL_IMAGE}
    container_name: surge-multicall-deployer
    pull_policy: always
    volumes:
      - ./deployer:/deployer
      - ./deployment:/deployment
    entrypoint:
      - /bin/sh
      - -c
      - /deployer/deploy-multicall.sh
    env_file:
      - .env
    environment:
      FOUNDRY_PROFILE: layer1o
      BROADCAST: ${BROADCAST}
      VERIFY: ${VERIFY}
      SLOW: ${SLOW}
      VERIFY_ARG: ${VERIFY_ARG}
      FORK_URL: ${L1_ENDPOINT_HTTP}
      PRIVATE_KEY: ${PRIVATE_KEY}
    networks:
      - surge
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      com.kurtosistech.custom.logs_enabled: "true"
      com.kurtosistech.custom.custom_network: "devnet"
    profiles:
      - multicall-deployer

  surge-userops-submitter-deployer:
    image: ${PROTOCOL_IMAGE}
    container_name: surge-userops-submitter-deployer
    pull_policy: always
    volumes:
      - ./deployer:/deployer
      - ./deployment:/deployment
    entrypoint:
      - /bin/sh
      - -c
      - /deployer/deploy-userops-submitter.sh
    env_file:
      - .env
    environment:
      FOUNDRY_PROFILE: layer1o
      BROADCAST: ${BROADCAST}
      VERIFY: ${VERIFY}
      SLOW: ${SLOW}
      VERIFY_ARG: ${VERIFY_ARG}
      OWNER_ADDRESS: ${SUBMITTER_PUBLIC_KEY}
      FORK_URL: ${L1_ENDPOINT_HTTP}
      PRIVATE_KEY: ${PRIVATE_KEY}
    networks:
      - surge
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      com.kurtosistech.custom.logs_enabled: "true"
      com.kurtosistech.custom.custom_network: "devnet"
    profiles:
      - userops-submitter-deployer

  surge-genesis-generator:
    image: ${PROTOCOL_IMAGE}
    container_name: surge-genesis-generator
    pull_policy: always
    volumes:
      - ./deployer:/deployer
      - ./deployment:/deployment
    entrypoint:
      - /bin/sh
      - -c
      - /deployer/generate-genesis.sh
    env_file:
      - .env
    environment:
      # SEED_ADDRESS: ${PUBLIC_KEY}
      CONTRACT_OWNER: ${PUBLIC_KEY}
      CHAIN_ID: ${L2_CHAIN_ID}
      REMOTE_SIGNAL_SERVICE: ${SHASTA_SIGNAL_SERVICE}
      FORK_URL: ${L1_ENDPOINT_HTTP}
      PRIVATE_KEY: ${PRIVATE_KEY}
    networks:
      - surge
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      com.kurtosistech.custom.logs_enabled: "true"
      com.kurtosistech.custom.custom_network: "devnet"
    profiles:
      - genesis-generator
  
  surge-accept-ownership:
    image: ${PROTOCOL_IMAGE}
    container_name: surge-accept-ownership
    pull_policy: always
    volumes:
      - ./deployer:/deployer
      - ./deployment:/deployment
    entrypoint:
      - /bin/sh
      - -c
      - /deployer/accept-ownership.sh
    env_file:
      - .env
    environment:
      FOUNDRY_PROFILE: layer1
      BROADCAST: ${BROADCAST}
      VERIFY: ${VERIFY}
      VERIFY_ARG: ${VERIFY_ARG}
      CONTRACT_ADDRESSES: ${CONTRACT_ADDRESSES}
      FORK_URL: ${L1_ENDPOINT_HTTP}
      PRIVATE_KEY: ${PRIVATE_KEY}
    networks:
      - surge
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      com.kurtosistech.custom.logs_enabled: "true"
      com.kurtosistech.custom.custom_network: "devnet"
    profiles:
      - accept-ownership

  surge-switch-fork:
    image: ${PROTOCOL_IMAGE}
    container_name: surge-switch-fork
    pull_policy: always
    volumes:
      - ./deployer:/deployer
      - ./deployment:/deployment
    entrypoint:
      - /bin/sh
      - -c
      - /deployer/switch-fork.sh
    env_file:
      - .env
    environment:
      PRIVATE_KEY: ${PRIVATE_KEY}
    networks:
      - surge
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      com.kurtosistech.custom.logs_enabled: "true"
      com.kurtosistech.custom.custom_network: "devnet"
    profiles:
      - switch-fork

  surge-bond-deposit:
    image: ${PROTOCOL_IMAGE}
    container_name: surge-bond-deposit
    pull_policy: always
    volumes:
      - ./deployer:/deployer
      - ./deployment:/deployment
    entrypoint:
      - /bin/sh
      - -c
      - /deployer/deposit-bond.sh
    env_file:
      - .env
    environment:
      SURGE_PROPOSER_WRAPPER: ${SURGE_PROPOSER_WRAPPER}
      ADMIN: ${PUBLIC_KEY}
      BOND_AMOUNT: ${BOND_AMOUNT:-1000}
      TAIKO_INBOX: ${TAIKO_INBOX}
    networks:
      - surge
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      com.kurtosistech.custom.logs_enabled: "true"
      com.kurtosistech.custom.custom_network: "devnet"
    profiles:
      - bond-deposit

  surge-zisk-setup:
    image: ${PROTOCOL_IMAGE}
    container_name: surge-zisk-setup
    pull_policy: always
    volumes:
      - ./deployer:/deployer
      - ./deployment:/deployment
    entrypoint:
      - /bin/sh
      - -c
      - /deployer/setup-zisk.sh
    env_file:
      - .env
    environment:
      FOUNDRY_PROFILE: layer1
      BROADCAST: ${BROADCAST}
      VERIFY: ${VERIFY}
      VERIFY_ARG: ${VERIFY_ARG}
      ZISK_VERIFIER_ADDRESS: ${ZISK_VERIFIER}
      ZISK_BATCH_VKEY: ${ZISK_BATCH_VKEY}
      FORK_URL: ${L1_ENDPOINT_HTTP}
    networks:
      - surge
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      com.kurtosistech.custom.logs_enabled: "true"
      com.kurtosistech.custom.custom_network: "devnet"
    profiles:
      - zisk-setup

  surge-risc0-verifier-setup:
    image: ${PROTOCOL_IMAGE}
    container_name: surge-risc0-verifier-setup
    pull_policy: always
    volumes:
      - ./deployer:/deployer
      - ./deployment:/deployment
    entrypoint:
      - /bin/sh
      - -c
      - /deployer/setup-risc0-verifier.sh
    env_file:
      - .env
    environment:
      FOUNDRY_PROFILE: layer1
      BROADCAST: ${BROADCAST}
      VERIFY: ${VERIFY}
      VERIFY_ARG: ${VERIFY_ARG}
      RISC0_VERIFIER_ADDRESS: ${RISC0_RETH_VERIFIER}
      RISC0_AGGREGATION_IMAGE_ID: ${RISC0_AGGREGATION_IMAGE_ID}
      RISC0_BLOCK_PROVING_IMAGE_ID: ${RISC0_BLOCK_PROVING_IMAGE_ID}
      NEW_OWNER: ${L1_OWNER}
      FORK_URL: ${L1_ENDPOINT_HTTP}
    networks:
      - surge
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      com.kurtosistech.custom.logs_enabled: "true"
      com.kurtosistech.custom.custom_network: "devnet"
    profiles:
      - risc0-verifier-setup

  surge-sp1-verifier-setup:
    image: ${PROTOCOL_IMAGE}
    container_name: surge-sp1-verifier-setup
    pull_policy: always
    volumes:
      - ./deployer:/deployer
      - ./deployment:/deployment
    entrypoint:
      - /bin/sh
      - -c
      - /deployer/setup-sp1-verifier.sh
    env_file:
      - .env
    environment:
      FOUNDRY_PROFILE: layer1
      BROADCAST: ${BROADCAST}
      VERIFY: ${VERIFY}
      VERIFY_ARG: ${VERIFY_ARG}
      SP1_VERIFIER_ADDRESS: ${SP1_RETH_VERIFIER}
      SP1_BLOCK_PROVING_PROGRAM_VKEY: ${SP1_BLOCK_PROVING_PROGRAM_VKEY}
      SP1_AGGREGATION_PROGRAM_VKEY: ${SP1_AGGREGATION_PROGRAM_VKEY}
      NEW_OWNER: ${L1_OWNER}
      FORK_URL: ${L1_ENDPOINT_HTTP}
    networks:
      - surge
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      com.kurtosistech.custom.logs_enabled: "true"
      com.kurtosistech.custom.custom_network: "devnet"
    profiles:
      - sp1-verifier-setup

networks:
  surge:
    name: surge-network
    external: true
