services:
  nethermind_execution_l2:
    image: nethermindeth/nethermind:surge-177139a04
    container_name: l2-nethermind-execution-client
    restart: unless-stopped
    pull_policy: always
    stop_grace_period: 3m
    tty: true
    volumes:
      - ./jwtsecret:/tmp/jwt/jwtsecret
      - ./chainspec.json:/chainspec.json
    networks:
      - surge
    ports:
      - ${L2_NETWORK_DISCOVERY_PORT}:${L2_NETWORK_DISCOVERY_PORT}/tcp
      - ${L2_NETWORK_DISCOVERY_PORT}:${L2_NETWORK_DISCOVERY_PORT}/udp
      - ${L2_METRICS_PORT}:${L2_METRICS_PORT}
      - ${L2_HTTP_PORT}:${L2_HTTP_PORT}
      - ${L2_WS_PORT}:${L2_WS_PORT}
      - ${L2_ENGINE_API_PORT}:${L2_ENGINE_API_PORT}
    command:
      - --config=none
      - --datadir=/data/taiko-geth
      - --Init.ChainSpecPath=/chainspec.json
      - --Init.GenesisHash=${L2_GENESIS_HASH}
      - --Init.DiscoveryEnabled=false
      - --Metrics.Enabled=true
      - --Metrics.ExposePort=${L2_METRICS_PORT}
      - --JsonRpc.Enabled=true
      - --JsonRpc.EnabledModules=[debug,eth,net,web3,txpool,rpc,subscribe,trace,personal,proof,parity,health]
      - --JsonRpc.Host=0.0.0.0
      - --JsonRpc.Port=${L2_HTTP_PORT}
      - --JsonRpc.WebSocketsPort=${L2_WS_PORT}
      - --JsonRpc.JwtSecretFile=/tmp/jwt/jwtsecret
      - --JsonRpc.EngineHost=0.0.0.0
      - --JsonRpc.EnginePort=${L2_ENGINE_API_PORT}
      - --Network.DiscoveryPort=${L2_NETWORK_DISCOVERY_PORT}
      - --Network.P2PPort=${L2_NETWORK_DISCOVERY_PORT}
      - --Sync.FastSync=false
      - --Sync.SnapSync=false
      - --HealthChecks.Enabled=true
      - --log=${NETHERMIND_LOG_LEVEL}
      - --JsonRpc.MaxBatchResponseBodySize=335544320
      - --JsonRpc.MaxBatchSize=102400
    profiles:
      - nethermind_execution_l2
      - proposer
      - prover

  taiko_client_driver:
    image: nethsurge/taiko-client:composite-proof-debug
    container_name: l2-taiko-consensus-client
    restart: unless-stopped
    pull_policy: always
    depends_on:
      - nethermind_execution_l2
    volumes:
      - ./execution-data-taiko:/data/taiko-geth
      - ./jwtsecret:/tmp/jwt/jwtsecret
    networks:
      - surge
    entrypoint:
      - taiko-client
    command:
      - driver
      - --l1.ws=${L1_ENDPOINT_WS}
      - --l2.ws=ws://l2-nethermind-execution-client:${L2_WS_PORT}
      - --l1.beacon=${L1_BEACON_HTTP}
      - --l2.auth=http://l2-nethermind-execution-client:${L2_ENGINE_API_PORT}
      - --taikoL1=${TAIKO_L1_ADDRESS}
      - --taikoL2=${TAIKO_L2_ADDRESS}
      - --jwtSecret=/tmp/jwt/jwtsecret
    profiles:
      - nethermind_execution_l2
      - proposer
      - prover

  taiko_client_proposer:
    image: nethsurge/taiko-client:composite-proof-debug
    container_name: l2-taiko-proposer-client
    restart: unless-stopped
    pull_policy: always
    depends_on:
      - nethermind_execution_l2
      - taiko_client_driver
    volumes:
      - ./execution-data-taiko:/data/taiko-geth
      - ./jwtsecret:/tmp/jwt/jwtsecret
    networks:
      - surge
    entrypoint:
      - taiko-client
    command:
      - proposer
      - --l1.ws=${L1_ENDPOINT_WS}
      - --l2.http=http://l2-nethermind-execution-client:${L2_HTTP_PORT}
      - --l2.auth=http://l2-nethermind-execution-client:${L2_ENGINE_API_PORT}
      - --taikoL1=${TAIKO_L1_ADDRESS}
      - --taikoL2=${TAIKO_L2_ADDRESS}
      - --jwtSecret=/tmp/jwt/jwtsecret
      - --l1.proposerPrivKey=${L1_PROPOSER_PRIVATE_KEY}
      - --l2.suggestedFeeRecipient=${L2_SUGGESTED_FEE_RECIPIENT}
      - --tx.notInMempoolTimeout=${TX_NOT_IN_MEMPOOL_TIMEOUT}
      - --tx.resubmissionTimeout=${TX_RESUBMISSION}
      - --epoch.interval=${EPOCH_INTERVAL}
      - --surge.gasNeededForProposingBlock=${PROPOSING_BLOCK_GAS}
      - --surge.gasNeededForProvingBlock=${PROVING_BLOCK_GAS}
      - --surge.offChainCosts=${OFF_CHAIN_COSTS}
      - --surge.priceFluctuationModifier=${PRICE_FLUCTUATION_MODIFIER}
    profiles:
      - proposer

  taiko_client_prover_relayer:
    image: nethsurge/taiko-client:composite-proof-debug
    container_name: l2-taiko-prover-relayer-client
    restart: unless-stopped
    pull_policy: always
    depends_on:
      - nethermind_execution_l2
      - taiko_client_driver
    networks:
      - surge
    entrypoint:
      - taiko-client
    command:
      - prover
      - --l1.ws=${L1_ENDPOINT_WS}
      - --l2.ws=ws://l2-nethermind-execution-client:${L2_WS_PORT}
      - --l2.http=http://l2-nethermind-execution-client:${L2_HTTP_PORT}
      - --taikoL1=${TAIKO_L1_ADDRESS}
      - --taikoL2=${TAIKO_L2_ADDRESS}
      - --l1.proverPrivKey=${L1_PROVER_PRIVATE_KEY}
      - --prover.capacity=${PROVER_CAPACITY}
      - --tx.notInMempoolTimeout=${TX_NOT_IN_MEMPOOL_TIMEOUT}
      - --tx.resubmissionTimeout=${TX_RESUBMISSION}
      - --sgxVerifier=${SGX_VERIFIER}
      - --sp1Verifier=${SP1_VERIFIER}
      - --risc0Verifier=${RISC0_VERIFIER}
      - --raiko.host.zkvm=${RAIKO_HOST_ZKVM}
      - --raiko.host=${SGX_RAIKO_HOST}
      - --raiko.requestTimeout=${RAIKO_REQUEST_TIMEOUT}
    profiles:
      - prover

networks:
  surge:
    name: surge-network
