global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
    - targets: ['pushgateway:9091']
  - job_name: 'nethermind'
    honor_labels: true
    static_configs:
    - targets: ['nethermind_execution_l2:8018']