global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'nethermind'
    honor_labels: true
    static_configs:
    - targets: ['nethermind_execution_l2:8018']
  - job_name: 'taiko-client'
    honor_labels: true
    static_configs:
    - targets: ['taiko_client_driver:6060']